#!/bin/bash
__help(){
	echo "Usage: ${CMD_NAME}"
	echo "       ${CMD_NAME} PATH"
	echo "This script is used to validate whether a path is a absolute path."
	echo ""
	echo "  PATH                         The path name to be validated"
	echo ""
	echo "This script validates only names. It doesn't matter whether the path exists or"
	echo "not."
	echo ""
	echo "If no option is specified, this help message is showed."
}
CMD_NAME="${0##*/}"
if [ $# -eq 0 ]
then
	__help
	exit 0
fi
if [ $# -gt 1 ]
then
	>&2 echo "${CMD_NAME}: too much arguments"
	>&2 echo "Try '${CMD_NAME}' for more information"
	exit 1
fi
if [ "${1:0:1}" == "/" ]
then
	echo "true"
else
	echo "false"
fi
exit 0
